on:
  push:
    branches: -master

  pull_request:
    branches: -master

jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install node 16
      uses: actions/setup-node
      with: 
       node-version: 16.x  

    - name: Install NPM Dependencies
      run : npm i 
    - name: Build Projects
       run: npm run build   
    - name: Upload artifact in order to deploy
      uses: actions/upload-artifact@v2
      with:
         name: production-files
         path: ./dist

  #Deploy Job
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: build

      steps:
       - name: Download artifact
        uses: actions/download-artifact@v2
        with:
         name: production-files
         path: ./dist

       - name: Deploy to github pages
         uses: peacerisis/actions-gh-pages@v3


